# Generated by Django 3.2.13 on 2022-07-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('DIN', 'Dining'), ('CIN', 'Cinema'), ('GAM', 'Gaming'), ('SPO', 'Sports'), ('CAM', 'Camping')], default='DIN', max_length=3)),
                ('location_online', models.BooleanField(default=False)),
                ('location_area', models.TextField()),
                ('location_time', models.DateTimeField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='event_attendees', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-location_time'],
            },
        ),
    ]
